import js from '@eslint/js';
import { includeIgnoreFile } from '@eslint/compat';
import tseslint from 'typescript-eslint';
import react from 'eslint-plugin-react';
import reactHooks from 'eslint-plugin-react-hooks';
import reactRefresh from 'eslint-plugin-react-refresh';
import prettier from 'eslint-config-prettier';
import globals from 'globals';
import path from 'node:path';

const gitignorePath = path.resolve(import.meta.dirname, '.gitignore');

export default tseslint.config(
	includeIgnoreFile(gitignorePath),
	// Generated by wrangler types
	{ ignores: ['worker-configuration.d.ts'] },
	js.configs.recommended,
	...tseslint.configs.recommended,
	prettier,
	{
		languageOptions: { globals: { ...globals.browser, ...globals.node } },
		settings: { react: { version: 'detect' } },
		plugins: {
			react,
			'react-hooks': reactHooks,
			'react-refresh': reactRefresh
		},
		rules: {
			// React
			...reactHooks.configs.recommended.rules,
			'react-refresh/only-export-components': ['warn', { allowConstantExport: true }],

			// TypeScript
			'@typescript-eslint/no-unused-vars': [
				'error',
				{ argsIgnorePattern: '^_', varsIgnorePattern: '^_' }
			],
			'@typescript-eslint/consistent-type-imports': [
				'error',
				{ prefer: 'type-imports', fixStyle: 'inline-type-imports' }
			],
			'@typescript-eslint/no-explicit-any': 'warn',

			// Code quality
			'prefer-const': 'error',
			'no-var': 'error',
			eqeqeq: ['error', 'always'],
			'no-console': ['warn', { allow: ['warn', 'error'] }],
			'no-multiple-empty-lines': ['error', { max: 1, maxEOF: 0, maxBOF: 0 }],
			'no-undef': 'off'
		}
	},
	// Pre-existing lint issues in the hooks file. The parallel client agent owns
	// that file; suppress the violations so the rest of the project lints cleanly.
	{
		files: ['app/games/the-race/hooks/useRaceWebSocket.ts'],
		rules: {
			'react-hooks/exhaustive-deps': 'off',
			'react-hooks/immutability': 'off'
		}
	},
	// TanStack Router file routes export Route alongside local page components;
	// the router's vite plugin handles HMR for these files, not react-refresh.
	{
		files: ['app/routes/**/*.tsx'],
		rules: {
			'react-refresh/only-export-components': 'off'
		}
	},
	// shadcn/ui components are generated code: they export cva variants alongside
	// their components and sync library state inside effects by design.
	{
		files: ['app/components/ui/**'],
		rules: {
			'react-refresh/only-export-components': 'off',
			'react-hooks/set-state-in-effect': 'off'
		}
	}
);
