/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ShmoneyRouteImport } from './routes/shmoney'
import { Route as PhotographyRouteImport } from './routes/photography'
import { Route as DevelopmentRouteImport } from './routes/development'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WritingIndexRouteImport } from './routes/writing/index'
import { Route as WritingFeedDotxmlRouteImport } from './routes/writing/feed[.]xml'
import { Route as WritingSlugRouteImport } from './routes/writing/$slug'

const ShmoneyRoute = ShmoneyRouteImport.update({
  id: '/shmoney',
  path: '/shmoney',
  getParentRoute: () => rootRouteImport,
} as any)
const PhotographyRoute = PhotographyRouteImport.update({
  id: '/photography',
  path: '/photography',
  getParentRoute: () => rootRouteImport,
} as any)
const DevelopmentRoute = DevelopmentRouteImport.update({
  id: '/development',
  path: '/development',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WritingIndexRoute = WritingIndexRouteImport.update({
  id: '/writing/',
  path: '/writing/',
  getParentRoute: () => rootRouteImport,
} as any)
const WritingFeedDotxmlRoute = WritingFeedDotxmlRouteImport.update({
  id: '/writing/feed.xml',
  path: '/writing/feed.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const WritingSlugRoute = WritingSlugRouteImport.update({
  id: '/writing/$slug',
  path: '/writing/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/development': typeof DevelopmentRoute
  '/photography': typeof PhotographyRoute
  '/shmoney': typeof ShmoneyRoute
  '/writing/$slug': typeof WritingSlugRoute
  '/writing/feed.xml': typeof WritingFeedDotxmlRoute
  '/writing/': typeof WritingIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/development': typeof DevelopmentRoute
  '/photography': typeof PhotographyRoute
  '/shmoney': typeof ShmoneyRoute
  '/writing/$slug': typeof WritingSlugRoute
  '/writing/feed.xml': typeof WritingFeedDotxmlRoute
  '/writing': typeof WritingIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/development': typeof DevelopmentRoute
  '/photography': typeof PhotographyRoute
  '/shmoney': typeof ShmoneyRoute
  '/writing/$slug': typeof WritingSlugRoute
  '/writing/feed.xml': typeof WritingFeedDotxmlRoute
  '/writing/': typeof WritingIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/development'
    | '/photography'
    | '/shmoney'
    | '/writing/$slug'
    | '/writing/feed.xml'
    | '/writing/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/development'
    | '/photography'
    | '/shmoney'
    | '/writing/$slug'
    | '/writing/feed.xml'
    | '/writing'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/development'
    | '/photography'
    | '/shmoney'
    | '/writing/$slug'
    | '/writing/feed.xml'
    | '/writing/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  DevelopmentRoute: typeof DevelopmentRoute
  PhotographyRoute: typeof PhotographyRoute
  ShmoneyRoute: typeof ShmoneyRoute
  WritingSlugRoute: typeof WritingSlugRoute
  WritingFeedDotxmlRoute: typeof WritingFeedDotxmlRoute
  WritingIndexRoute: typeof WritingIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/shmoney': {
      id: '/shmoney'
      path: '/shmoney'
      fullPath: '/shmoney'
      preLoaderRoute: typeof ShmoneyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/photography': {
      id: '/photography'
      path: '/photography'
      fullPath: '/photography'
      preLoaderRoute: typeof PhotographyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/development': {
      id: '/development'
      path: '/development'
      fullPath: '/development'
      preLoaderRoute: typeof DevelopmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/writing/': {
      id: '/writing/'
      path: '/writing'
      fullPath: '/writing/'
      preLoaderRoute: typeof WritingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/writing/feed.xml': {
      id: '/writing/feed.xml'
      path: '/writing/feed.xml'
      fullPath: '/writing/feed.xml'
      preLoaderRoute: typeof WritingFeedDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/writing/$slug': {
      id: '/writing/$slug'
      path: '/writing/$slug'
      fullPath: '/writing/$slug'
      preLoaderRoute: typeof WritingSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  DevelopmentRoute: DevelopmentRoute,
  PhotographyRoute: PhotographyRoute,
  ShmoneyRoute: ShmoneyRoute,
  WritingSlugRoute: WritingSlugRoute,
  WritingFeedDotxmlRoute: WritingFeedDotxmlRoute,
  WritingIndexRoute: WritingIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
