/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const WorkLazyImport = createFileRoute('/work')()
const IracingLazyImport = createFileRoute('/iracing')()
const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const WorkLazyRoute = WorkLazyImport.update({
  id: '/work',
  path: '/work',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/work.lazy').then((d) => d.Route))

const IracingLazyRoute = IracingLazyImport.update({
  id: '/iracing',
  path: '/iracing',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/iracing.lazy').then((d) => d.Route))

const IndexLazyRoute = IndexLazyImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/iracing': {
      id: '/iracing'
      path: '/iracing'
      fullPath: '/iracing'
      preLoaderRoute: typeof IracingLazyImport
      parentRoute: typeof rootRoute
    }
    '/work': {
      id: '/work'
      path: '/work'
      fullPath: '/work'
      preLoaderRoute: typeof WorkLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/iracing': typeof IracingLazyRoute
  '/work': typeof WorkLazyRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/iracing': typeof IracingLazyRoute
  '/work': typeof WorkLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/iracing': typeof IracingLazyRoute
  '/work': typeof WorkLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/iracing' | '/work'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/iracing' | '/work'
  id: '__root__' | '/' | '/iracing' | '/work'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  IracingLazyRoute: typeof IracingLazyRoute
  WorkLazyRoute: typeof WorkLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  IracingLazyRoute: IracingLazyRoute,
  WorkLazyRoute: WorkLazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/iracing",
        "/work"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/iracing": {
      "filePath": "iracing.lazy.tsx"
    },
    "/work": {
      "filePath": "work.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
